import { useState, useEffect } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export let currentLanguage = "English";
const listeners = new Set<(lang: string) => void>();

export const initLanguage = async () => {
  try {
    const saved = await AsyncStorage.getItem("app_language");
    if (saved && translations[saved]) {
      currentLanguage = saved;
      listeners.forEach((listener) => listener(saved));
      console.log("[Localization] Loaded persisted language:", saved);
    }
  } catch (e) {
    console.log("[Localization] Failed to load language", e);
  }
};

export const setCurrentLanguage = async (lang: string) => {
  currentLanguage = lang;
  listeners.forEach((listener) => listener(lang));
  console.log("[Localization] Globally active language updated:", currentLanguage);
  try {
    await AsyncStorage.setItem("app_language", lang);
  } catch (e) {
    console.log("[Localization] Failed to save language", e);
  }
};

export const translations: Record<string, Record<string, string>> = {
  English: {
    // Navigation / Tabs
    "home": "Home",
    "datasets": "Datasets",
    "analysis": "Analysis",
    "tools": "Tools",
    "profile": "Profile",
    "history": "History",
    "favorites": "Favorites",
    "insights": "Insights",

    // General & Onboarding
    "welcome": "Welcome to ResearchMateAI",
    "continue": "Continue",
    "skip": "Skip",
    "next": "Next",
    "get_started": "Get Started",
    "onboarding1_title": "Generate Research Ideas",
    "onboarding1_sub": "Get smart topic suggestions tailored to your department and domain in seconds.",
    "onboarding2_title": "Discover Relevant Datasets",
    "onboarding2_sub": "Search thousands of research datasets from trusted sources instantly.",
    "onboarding3_title": "Analyze & Improve Content",
    "onboarding3_sub": "Upload datasets, analyze results and paraphrase academic content easily.",

    // Authentication
    "welcome_back": "Welcome Back 👋",
    "login_phone_title": "Login with your phone number",
    "enter_phone_placeholder": "Enter phone number",
    "sendOtp": "Send OTP",
    "or": "OR",
    "continue_google": "Continue with Google",
    "verify_otp_header": "Verify OTP",
    "verify_otp_desc": "Enter the 4-digit code sent to your mobile number",
    "verify": "Verify & Login",
    "resend_otp": "Resend OTP",

    // Dashboard Home
    "ai_research_assistant": "AI Research Assistant",
    "smart_tools_desc": "Smart tools for academic success",
    "quick_access": "Quick Access",
    "title_generator": "Title Generator",
    "generate_topics_desc": "Generate research topics",
    "explore_datasets": "Explore datasets",
    "analyze_csv_desc": "Analyze CSV data",
    "rewrite_content": "Rewrite content",

    // Title Generator Screen
    "research_title_gen": "Research Title Generator",
    "title_gen_subtitle": "Generate AI-powered project and research ideas instantly",
    "department_label": "Department",
    "domain_label": "Domain",
    "generate_btn": "Generate Titles",
    "generated_topics": "Generated Topics",
    "see_all": "See All",
    "generated_just_now": "Generated just now",
    "open": "Open",
    "empty_state_title": "Start generating research titles",
    "empty_state_sub": "Pick your department and domain, then tap Generate Titles.",
    "select_dept_modal": "Select Department",
    "select_domain_modal": "Select Domain",

    // Dataset Screen
    "discover_datasets": "Discover Datasets",
    "find_datasets_subtitle": "Find datasets for research and AI projects",
    "search_dataset_placeholder": "Search datasets...",
    "fetching_datasets": "Fetching premium datasets...",
    "search_failed": "Search Failed",
    "retry_search": "Retry Search",
    "no_datasets_found": "No Datasets Found",
    "try_another_topic": "Try searching for another topic like 'climate', 'health', or 'finance'",
    "open_dataset": "Open Dataset",

    // CSV Analysis Screen
    "dataset_report": "Dataset Report",
    "csv_analysis": "CSV Analysis",
    "upload_analyze_subtitle": "Upload and analyze research datasets",
    "upload_csv": "Upload CSV File",
    "select_dataset_analysis": "Select your dataset for AI-powered analysis",
    "analyzing": "Analyzing...",
    "choose_csv": "Choose CSV",
    "uploading_parsing": "Uploading & parsing dataset...",

    // Academic Paraphraser Screen
    "ai_paraphraser": "AI Paraphraser",
    "rewrite_text_subtitle": "Rewrite text with multiple writing styles",
    "paste_or_type": "Paste or type text here...",
    "characters": "characters",
    "words": "words",
    "max_words_warning": "Maximum 200 words allowed. Please trim your text.",
    "paste": "Paste",
    "copied": "Copied",
    "copy_input": "Copy Input",
    "copy_output": "Copy Output",
    "clear": "Clear",
    "paraphrase_btn": "Paraphrase",
    "output_title": "Output",
    "compare_versions": "Compare Versions",
    "mode_label": "Mode",
    "mode_standard": "Standard",
    "mode_fluency": "Fluency",
    "mode_formal": "Formal",
    "mode_academic": "Academic",
    "mode_creative": "Creative",
    "mode_expand": "Expand",
    "mode_shorten": "Shorten",
    "mode_simple": "Simple",
    "words_label": "Words",
    "regenerate": "Regenerate",
    "swap_text": "Swap Text",
    "no_history_yet": "No history yet",
    "history_stored_locally": "Paraphrased items will be automatically stored locally.",
    "paraphrase_now": "Paraphrase Now",
    "no_favorites_saved": "No favorites saved",
    "star_records_desc": "Star records in History to save them for quick reference here.",
    "view_history": "View History",
    "writing_insights": "Writing Insights",
    "refresh": "Refresh",
    "analyzing_insights": "Analyzing grammar, readability & tone...",
    "no_text_analyze": "No text to analyze",
    "write_text_now": "Write Text Now",
    "readability_analysis": "Readability Analysis",
    "writing_tone": "Writing Tone",
    "confidence_label": "confidence",
    "grammar_mechanics": "Grammar & Mechanics",
    "clean_grammar_desc": "Your grammar is clean! No spelling or spacing errors detected.",
    "style_recommendations": "Style Recommendations",
    "clean_style_desc": "Excellent writing style! No stylistic flow suggestions.",
    "removals": "Removals",
    "additions": "Additions",
    "modified_synonyms": "Modified/Synonyms",
    "original_text_title": "Original Text",
    "paraphrased_text_title": "Paraphrased Text",
    "paraphrase_details": "Paraphrase Details",
    "original": "Original",
    "paraphrased": "Paraphrased",
    "created_at": "Created",
    "delete": "Delete",
    "favorite": "Favorite",
    "unstar": "Unstar",
    "reuse": "Reuse",
    "done": "Done",

    // Research Explorer Screen
    "research_explorer": "Research Explorer",
    "search_papers_placeholder": "Search papers, authors, DOI...",
    "trending_topics": "Trending Topics",
    "research": "Research",
    "explore_research_papers": "Explore Research Papers",

    // Profile Screen
    "profile_header": "Profile",
    "preferences": "Preferences",
    "notifications": "Notifications",
    "dark_mode": "Dark Mode",
    "quick_actions": "Quick Actions",
    "edit_profile": "Edit Profile",
    "app_settings": "App Settings",
    "language": "Language",
    "language_subtitle": "Select your preferred language for the application interface",
    "help_support": "Help & Support",
    "logout": "Logout",

    // Help & Support Screen
    "faq_title": "Frequently Asked Questions",
    "faq_sub": "Quick answers to help you navigate ResearchMateAI",
    "faq_q1": "How do I upload a CSV?",
    "faq_a1": "Navigate to the 'Analysis' tab, click 'Choose CSV', and pick any valid dataset file from your device storage to generate immediate statistical reports.",
    "faq_q2": "How does the Paraphraser work?",
    "faq_a2": "It uses an advanced semantic-preserving academic engine to rewrite text in custom writing styles without altering original facts or context.",
    "faq_q3": "Can I bookmark research titles?",
    "faq_a3": "Yes! Simply click the bookmark icon on any generated research topic card to save it instantly to your favorites collection.",
    "faq_q4": "Where is my research history saved?",
    "faq_a4": "All your academic paraphrases, insights, and datasets are securely saved locally on your local host server.",
    "submit_ticket": "Submit a Support Ticket",
    "submit_ticket_sub": "Need custom help? Send our team a detailed inquiry.",
    "request_type": "Request Type",
    "bug_report": "Bug Report",
    "feature_request": "Feature Request",
    "question": "Question",
    "email_address": "Your Email Address",
    "email_placeholder": "e.g. researcher@university.edu",
    "message_details": "Message Details",
    "message_placeholder": "Describe your issue or request in detail...",
    "submit_request": "Submit Support Request",
    "required_fields": "Required Fields",
    "required_fields_message": "Please enter both your email and feedback message.",
    "invalid_email": "Invalid Email",
    "invalid_email_message": "Please enter a valid email address.",
    "ticket_submitted": "Ticket Submitted",
    "ticket_submitted_message": "Your support request has been registered. Our support team will contact you shortly!",

    // Additions for missing strings
    "email_address_placeholder": "Email Address",
    "password_placeholder": "Password",
    "first_name_placeholder": "First Name",
    "last_name_placeholder": "Last Name",
    "username_placeholder": "Username",
    "mobile_number_placeholder": "Mobile Number",
    "confirm_password_placeholder": "Confirm Password",
    "forgot_password_btn": "Forgot Password?",
    "send_reset_code": "Send Reset Code",
    "verify_code": "Verify Code",
    "new_password_placeholder": "New Password",
    "confirm_new_password_placeholder": "Confirm New Password",
    "save_new_password": "Save New Password",
    "cancel_back_to_login": "Cancel & Back to Login",
    "back_to_login": "Back to Login",
    "login_btn": "Login",
    "signup_btn": "Sign Up",
    "verify_otp_btn": "Verify OTP",
    "full_name_placeholder": "Full Name",
    "bio_placeholder": "Bio (e.g. Data Scientist / AI Researcher)",
    "save_profile_btn": "Save Profile",
    "search_saved_placeholder": "Search by title, domain, dept...",
    "open_plan_btn": "Open Plan",
    "research_dashboard_title": "Research Dashboard",
    "favorite_papers_title": "Favorite Papers",
    "paper_intelligence_title": "Paper Intelligence",
    "abstract_title": "Abstract",
    "key_findings_title": "Key Findings",
    "contributions_title": "Contributions",
    "configure_graph_labels": "Configure Graph Labels",
    "graph_title_label": "Graph Title",
    "x_axis_label": "X-Axis Label",
    "y_axis_label": "Y-Axis Label",
    "graph_title_placeholder": "e.g. Comparison graph",
    "x_axis_placeholder": "e.g. Parameters",
    "y_axis_placeholder": "e.g. Value",
    "save_labels_btn": "Save Labels"
  },
  Hindi: {
    // Navigation / Tabs
    "home": "होम",
    "datasets": "डेटासेट",
    "analysis": "विश्लेषण",
    "tools": "उपकरण",
    "profile": "प्रोफ़ाइल",
    "history": "इतिहास",
    "favorites": "पसंदीदा",
    "insights": "अंतर्दृष्टि",

    // General & Onboarding
    "welcome": "ResearchMateAI में आपका स्वागत है",
    "continue": "जारी रखें",
    "skip": "छोड़ें",
    "next": "आगे",
    "get_started": "शुरू करें",
    "onboarding1_title": "अनुसंधान विचार उत्पन्न करें",
    "onboarding1_sub": "सेकंड में अपने विभाग और डोमेन के अनुरूप स्मार्ट विषय सुझाव प्राप्त करें।",
    "onboarding2_title": "प्रासंगिक डेटासेट खोजें",
    "onboarding2_sub": "विश्वसनीय स्रोतों से हजारों शोध डेटासेट तुरंत खोजें।",
    "onboarding3_title": "सामग्री का विश्लेषण और सुधार करें",
    "onboarding3_sub": "डेटासेट अपलोड करें, परिणामों का विश्लेषण करें और अकादमिक सामग्री को आसानी से पैराफ़्रेज़ करें।",

    // Authentication
    "welcome_back": "वापसी पर स्वागत है 👋",
    "login_phone_title": "अपने फोन नंबर से लॉगिन करें",
    "enter_phone_placeholder": "फ़ोन नंबर दर्ज करें",
    "sendOtp": "ओटीपी भेजें",
    "or": "या",
    "continue_google": "गूगल के साथ जारी रखें",
    "verify_otp_header": "ओटीपी सत्यापित करें",
    "verify_otp_desc": "अपने मोबाइल नंबर पर भेजा गया 4-अंकीय कोड दर्ज करें",
    "verify": "सत्यापित करें और लॉगिन करें",
    "resend_otp": "ओटीपी पुनः भेजें",

    // Dashboard Home
    "ai_research_assistant": "एआई अनुसंधान सहायक",
    "smart_tools_desc": "अकादमिक सफलता के लिए स्मार्ट उपकरण",
    "quick_access": "त्वरित पहुँच",
    "title_generator": "शीर्षक जनरेटर",
    "generate_topics_desc": "अनुसंधान विषय उत्पन्न करें",
    "explore_datasets": "डेटासेट का अन्वेषण करें",
    "analyze_csv_desc": "सीएसवी डेटा का विश्लेषण करें",
    "rewrite_content": "सामग्री को फिर से लिखें",

    // Title Generator Screen
    "research_title_gen": "अनुसंधान शीर्षक जनरेटर",
    "title_gen_subtitle": "तुरंत एआई-संचालित परियोजना और अनुसंधान विचार उत्पन्न करें",
    "department_label": "विभाग",
    "domain_label": "डोमेन",
    "generate_btn": "शीर्षक उत्पन्न करें",
    "generated_topics": "उत्पन्न विषय",
    "see_all": "सभी देखें",
    "generated_just_now": "अभी उत्पन्न किया गया",
    "open": "खोलें",
    "empty_state_title": "अनुसंधान शीर्षक उत्पन्न करना शुरू करें",
    "empty_state_sub": "अपना विभाग और डोमेन चुनें, फिर शीर्षक उत्पन्न करें पर टैप करें।",
    "select_dept_modal": "विभाग चुनें",
    "select_domain_modal": "डोमेन चुनें",
    "research": "अनुसंधान",
    "explore_research_papers": "शोध पत्रों का अन्वेषण करें",

    // Dataset Screen
    "discover_datasets": "डेटासेट खोजें",
    "find_datasets_subtitle": "अनुसंधान और एआई परियोजनाओं के लिए डेटासेट खोजें",
    "search_dataset_placeholder": "डेटासेट खोजें...",
    "fetching_datasets": "प्रीमियम डेटासेट प्राप्त किए जा रहे हैं...",
    "search_failed": "खोज विफल रही",
    "retry_search": "पुनः प्रयास करें",
    "no_datasets_found": "कोई डेटासेट नहीं मिला",
    "try_another_topic": "जलवायु, स्वास्थ्य या वित्त जैसे किसी अन्य विषय को खोजने का प्रयास करें",
    "open_dataset": "डेटासेट खोलें",

    // CSV Analysis Screen
    "dataset_report": "डेटासेट रिपोर्ट",
    "csv_analysis": "सीएसवी विश्लेषण",
    "upload_analyze_subtitle": "अनुसंधान डेटासेट अपलोड करें और विश्लेषण करें",
    "upload_csv": "सीएसवी फाइल अपलोड करें",
    "select_dataset_analysis": "एआई-संचालित विश्लेषण के लिए अपना डेटासेट चुनें",
    "analyzing": "विश्लेषण किया जा रहा है...",
    "choose_csv": "सीएसवी चुनें",
    "uploading_parsing": "डेटासेट अपलोड और पार्स किया जा रहा है...",

    // Academic Paraphraser Screen
    "ai_paraphraser": "एआई पैराफ्रासर",
    "rewrite_text_subtitle": "कई लेखन शैलियों के साथ पाठ को फिर से लिखें",
    "paste_or_type": "यहाँ पाठ पेस्ट करें या टाइप करें...",
    "characters": "वर्ण",
    "words": "शब्द",
    "max_words_warning": "अधिकतम 200 शब्दों की अनुमति है। कृपया अपने पाठ को छोटा करें।",
    "paste": "पेस्ट",
    "copied": "कॉपी किया गया",
    "copy_input": "इनपुट कॉपी करें",
    "copy_output": "आउटपुट कॉपी करें",
    "clear": "साफ़ करें",
    "paraphrase_btn": "पैराफ़्रेज़",
    "output_title": "आउटपुट",
    "compare_versions": "संस्करणों की तुलना करें",
    "mode_label": "मोड",
    "mode_standard": "मानक",
    "mode_fluency": "प्रवाह",
    "mode_formal": "औपचारिक",
    "mode_academic": "अकादमिक",
    "mode_creative": "रचनात्मक",
    "mode_expand": "विस्तार करें",
    "mode_shorten": "संक्षिप्त करें",
    "mode_simple": "सरल",
    "words_label": "शब्द",
    "regenerate": "पुनः उत्पन्न करें",
    "swap_text": "पाठ बदलें",
    "no_history_yet": "अभी तक कोई इतिहास नहीं",
    "history_stored_locally": "पैराफ़्रेज़ की गई वस्तुएं स्वचालित रूप से स्थानीय रूप से संग्रहीत की जाएंगी।",
    "paraphrase_now": "अभी पैराफ़्रेज़ करें",
    "no_favorites_saved": "कोई पसंदीदा सहेज नहीं गया",
    "star_records_desc": "त्वरित संदर्भ के लिए उन्हें सहेजने के लिए इतिहास में स्टार रिकॉर्ड करें।",
    "view_history": "इतिहास देखें",
    "writing_insights": "लेखन अंतर्दृष्टि",
    "refresh": "ताज़ा करें",
    "analyzing_insights": "व्याकरण, पठनीयता और स्वर का विश्लेषण किया जा रहा है...",
    "no_text_analyze": "विश्लेषण के लिए कोई पाठ नहीं",
    "write_text_now": "अभी पाठ लिखें",
    "readability_analysis": "पठनीयता विश्लेषण",
    "writing_tone": "लेखन स्वर",
    "confidence_label": "विश्वास",
    "grammar_mechanics": "व्याकरण और मैकेनिक्स",
    "clean_grammar_desc": "आपका व्याकरण साफ है! कोई वर्तनी या रिक्ति त्रुटि नहीं पाई गई।",
    "style_recommendations": "शैली अनुशंसाएँ",
    "clean_style_desc": "उत्कृष्ट लेखन शैली! कोई शैलीगत प्रवाह सुझाव नहीं।",
    "removals": "हटाए गए",
    "additions": "जोड़े गए",
    "modified_synonyms": "संशोधित/समानार्थी",
    "original_text_title": "मूल पाठ",
    "paraphrased_text_title": "पैराफ़्रेज़ किया गया पाठ",
    "paraphrase_details": "पैराफ़्रेज़ विवरण",
    "original": "मूल",
    "paraphrased": "पैराफ़्रेज़ किया गया",
    "created_at": "निर्मित",
    "delete": "हटाएं",
    "favorite": "पसंदीदा",
    "unstar": "अनस्टार",
    "reuse": "पुनः उपयोग",
    "done": "हो गया",

    // Profile Screen
    "profile_header": "प्रोफ़ाइल",
    "preferences": "वरीयताएँ",
    "notifications": "सूचनाएं",
    "dark_mode": "डार्क मोड",
    "quick_actions": "त्वरित कार्य",
    "edit_profile": "प्रोफ़ाइल संपादित करें",
    "app_settings": "ऐप सेटिंग्स",
    "language": "भाषा",
    "language_subtitle": "एप्लिकेशन इंटरफ़ेस के लिए अपनी पसंदीदा भाषा चुनें",
    "help_support": "सहायता और समर्थन",
    "logout": "लॉग आउट",

    // Help & Support Screen
    "faq_title": "अक्सर पूछे जाने वाले प्रश्न",
    "faq_sub": "ResearchMateAI को नेविगेट करने में आपकी सहायता के लिए त्वरित उत्तर",
    "faq_q1": "मैं सीएसवी कैसे अपलोड करूं?",
    "faq_a1": "'विश्लेषण' टैब पर जाएं, 'सीएसवी चुनें' पर क्लिक करें, और तत्काल सांख्यिकीय रिपोर्ट उत्पन्न करने के लिए अपने डिवाइस स्टोरेज से कोई भी मान्य डेटासेट फ़ाइल चुनें।",
    "faq_q2": "पैराफ्रासर कैसे काम करता है?",
    "faq_a2": "यह मूल तथ्यों या संदर्भ को बदले बिना कस्टम लेखन शैलियों में पाठ को फिर से लिखने के लिए एक उन्नत अर्थ-संरक्षण शैक्षणिक इंजन का उपयोग करता है।",
    "faq_q3": "क्या मैं शोध शीर्षकों को बुकमार्क कर सकता हूँ?",
    "faq_a3": "हाँ! किसी भी उत्पन्न शोध विषय कार्ड पर बुकमार्क आइकन पर क्लिक करके इसे तुरंत अपने पसंदीदा संग्रह में सहेजें।",
    "faq_q4": "मेरा शोध इतिहास कहां सहेजा गया है?",
    "faq_a4": "आपके सभी शैक्षणिक पैराफ़्रेज़, अंतर्दृष्टि और डेटासेट आपके स्थानीय होस्ट सर्वर पर सुरक्षित रूप से स्थानीय रूप से सहेजे गए हैं।",
    "submit_ticket": "एक सहायता टिकट जमा करें",
    "submit_ticket_sub": "कस्टम सहायता चाहिए? हमारी टीम को एक विस्तृत पूछताछ भेजें।",
    "request_type": "अनुरोध प्रकार",
    "bug_report": "बग रिपोर्ट",
    "feature_request": "सुविधा अनुरोध",
    "question": "प्रश्न",
    "email_address": "आपका ईमेल पता",
    "email_placeholder": "जैसे: researcher@university.edu",
    "message_details": "संदेश विवरण",
    "message_placeholder": "अपनी समस्या या अनुरोध का विस्तार से वर्णन करें...",
    "submit_request": "सहायता अनुरोध सबमिट करें",
    "required_fields": "आवश्यक फ़ील्ड",
    "required_fields_message": "कृपया अपना ईमेल और फीडबैक संदेश दोनों दर्ज करें।",
    "invalid_email": "अमान्य ईमेल",
    "invalid_email_message": "कृपया एक मान्य ईमेल पता दर्ज करें।",
    "ticket_submitted": "टिकट जमा किया गया",
    "ticket_submitted_message": "आपका सहायता अनुरोध दर्ज कर लिया गया है। हमारी सहायता टीम जल्द ही आपसे संपर्क करेगी!",

    // Additions for missing strings
    "email_address_placeholder": "ईमेल पता",
    "password_placeholder": "पासवर्ड",
    "first_name_placeholder": "पहला नाम",
    "last_name_placeholder": "अंतिम नाम",
    "username_placeholder": "उपयोगकर्ता नाम",
    "mobile_number_placeholder": "मोबाइल नंबर",
    "confirm_password_placeholder": "पासवर्ड की पुष्टि करें",
    "forgot_password_btn": "पासवर्ड भूल गए?",
    "send_reset_code": "रीसेट कोड भेजें",
    "verify_code": "कोड सत्यापित करें",
    "new_password_placeholder": "नया पासवर्ड",
    "confirm_new_password_placeholder": "नया पासवर्ड की पुष्टि करें",
    "save_new_password": "नया पासवर्ड सहेजें",
    "cancel_back_to_login": "रद्द करें और लॉगिन पर वापस जाएं",
    "back_to_login": "लॉगिन पर वापस जाएं",
    "login_btn": "लॉगिन",
    "signup_btn": "साइन अप",
    "verify_otp_btn": "ओटीपी सत्यापित करें",
    "full_name_placeholder": "पूरा नाम",
    "bio_placeholder": "बायो (उदा. डेटा साइंटिस्ट)",
    "save_profile_btn": "प्रोफ़ाइल सहेजें",
    "search_saved_placeholder": "शीर्षक, डोमेन, विभाग द्वारा खोजें...",
    "open_plan_btn": "योजना खोलें",
    "research_dashboard_title": "अनुसंधान डैशबोर्ड",
    "favorite_papers_title": "पसंदीदा पेपर",
    "paper_intelligence_title": "पेपर इंटेलिजेंस",
    "abstract_title": "सार",
    "key_findings_title": "मुख्य निष्कर्ष",
    "contributions_title": "योगदान",
    "configure_graph_labels": "ग्राफ लेबल कॉन्फ़िगर करें",
    "graph_title_label": "ग्राफ का शीर्षक",
    "x_axis_label": "एक्स-एक्सिस लेबल",
    "y_axis_label": "वाई-एक्सिस लेबल",
    "graph_title_placeholder": "उदा. तुलना ग्राफ",
    "x_axis_placeholder": "उदा. पैरामीटर",
    "y_axis_placeholder": "उदा. मूल्य",
    "save_labels_btn": "लेबल सहेजें"
  },
  Telugu: {
    // Navigation / Tabs
    "home": "హోమ్",
    "datasets": "డేటాసెట్లు",
    "analysis": "విశ్లేషణ",
    "tools": "ఉపకరణాలు",
    "profile": "ప్రొఫైల్",
    "history": "చరిత్ర",
    "favorites": "ఇష్టమైనవి",
    "insights": "అంతర్దృష్టులు",

    // General & Onboarding
    "welcome": "ResearchMateAI కి స్వాగతం",
    "continue": "కొనసాగించు",
    "skip": "దాటవేయి",
    "next": "తరువాత",
    "get_started": "ప్రారంభించండి",
    "onboarding1_title": "పరిశోధన ఆలోచనలను సృష్టించండి",
    "onboarding1_sub": "మీ విభాగం మరియు రంగానికి అనుగుణంగా స్మార్ట్ టాపిక్ సూచనలను సెకన్లలో పొందండి.",
    "onboarding2_title": "సంబంధిత డేటాసెట్లను కనుగొనండి",
    "onboarding2_sub": "విశ్వసనీయ వనరుల నుండి వేలాది పరిశోధన డేటాసెట్లను తక్షణమే శోధించండి.",
    "onboarding3_title": "కంటెంట్‌ను విశ్లేషించండి & మెరుగుపరచండి",
    "onboarding3_sub": "డేటాసెట్లను అప్‌లోడ్ చేయండి, ఫలితాలను విశ్లేషించండి మరియు అకడమిక్ కంటెంట్‌ను సులభంగా పారాఫ్రేస్ చేయండి.",

    // Authentication
    "welcome_back": "తిరిగి స్వాగతం 👋",
    "login_phone_title": "మీ ఫోన్ నంబర్‌తో లాగిన్ అవ్వండి",
    "enter_phone_placeholder": "ఫోన్ నంబర్ నమోదు చేయండి",
    "sendOtp": "OTP పంపండి",
    "or": "లేదా",
    "continue_google": "గూగుల్‌తో కొనసాగండి",
    "verify_otp_header": "OTP ధృవీకరించండి",
    "verify_otp_desc": "మీ మొబైల్ నంబర్‌కు పంపిన 4-అంకెల కోడ్‌ను నమోదు చేయండి",
    "verify": "ధృవీకరించండి & లాగిన్",
    "resend_otp": "OTP ని మళ్లీ పంపండి",

    // Dashboard Home
    "ai_research_assistant": "AI పరిశోధన సహాయకుడు",
    "smart_tools_desc": "విద్యా విజయానికి స్మార్ట్ సాధనాలు",
    "quick_access": "త్వరిత ప్రాప్యత",
    "title_generator": "టైటిల్ జనరేటర్",
    "generate_topics_desc": "పరిశోధన అంశాలను సృష్టించండి",
    "explore_datasets": "డేటాసెట్లను అన్వేషించండి",
    "analyze_csv_desc": "CSV డేటాను విశ్లేషించండి",
    "rewrite_content": "కంటెంట్‌ను తిరిగి రాయండి",

    // Title Generator Screen
    "research_title_gen": "పరిశోధన శీర్షిక జనరేటర్",
    "title_gen_subtitle": "AI-ఆధారిత ప్రాజెక్ట్ మరియు పరిశోధన ఆలోచనలను తక్షణమే సృష్టించండి",
    "department_label": "విభాగం",
    "domain_label": "రంగం",
    "generate_btn": "శీర్షికలను సృష్టించండి",
    "generated_topics": "సృష్టించబడిన అంశాలు",
    "see_all": "అన్నీ చూడండి",
    "generated_just_now": "ఇప్పుడే సృష్టించబడింది",
    "open": "ఓపెన్",
    "empty_state_title": "పరిశోధన శీర్షికలను సృష్టించడం ప్రారంభించండి",
    "empty_state_sub": "మీ విభాగం మరియు రంగాన్ని ఎంచుకోండి, ఆపై శీర్షికలను సృష్టించండి నొక్కండి.",
    "select_dept_modal": "విభాగం ఎంచుకోండి",
    "select_domain_modal": "రంగం ఎంచుకోండి",
    "research": "పరిశోధన",
    "explore_research_papers": "పరిశోధనా పత్రాలను అన్వేషించండి",

    // Dataset Screen
    "discover_datasets": "డేటాసెట్లను కనుగొనండి",
    "find_datasets_subtitle": "పరిశోధన మరియు AI ప్రాజెక్టుల కోసం డేటాసెట్లను కనుగొనండి",
    "search_dataset_placeholder": "డేటాసెట్లను శోధించండి...",
    "fetching_datasets": "ప్రీమియం డేటాసెట్లను తీసుకువస్తోంది...",
    "search_failed": "శోధన విఫలమైంది",
    "retry_search": "మళ్లీ శోధించండి",
    "no_datasets_found": "డేటాసెట్లు కనుగొనబడలేదు",
    "try_another_topic": "'వాతావరణం', 'ఆరోగ్యం' లేదా 'ఆర్థికం' వంటి మరొక అంశాన్ని శోధించడానికి ప్రయత్నించండి",
    "open_dataset": "డేటాసెట్ ఓపెన్ చేయండి",

    // CSV Analysis Screen
    "dataset_report": "డేటాసెట్ నివేదిక",
    "csv_analysis": "CSV విశ్లేషణ",
    "upload_analyze_subtitle": "పరిశోధన డేటాసెట్లను అప్‌లోడ్ చేయండి మరియు విశ్లేషించండి",
    "upload_csv": "CSV ఫైల్‌ను అప్‌లోడ్ చేయండి",
    "select_dataset_analysis": "AI-ఆధారిత విశ్లేషణ కోసం మీ డేటాసెట్‌ను ఎంచుకోండి",
    "analyzing": "విశ్లేషిస్తోంది...",
    "choose_csv": "CSV ని ఎంచుకోండి",
    "uploading_parsing": "డేటాసెట్‌ను అప్‌లోడ్ చేస్తోంది & పార్స్ చేస్తోంది...",

    // Academic Paraphraser Screen
    "ai_paraphraser": "AI పారాఫ్రేసర్",
    "rewrite_text_subtitle": "బహుళ వ్రాత శైలులతో వచనాన్ని తిరిగి రాయండి",
    "paste_or_type": "మీ వచనాన్ని ఇక్కడ అతికించండి లేదా టైప్ చేయండి...",
    "characters": "అక్షరాలు",
    "words": "పదాలు",
    "max_words_warning": "గరిష్టంగా 200 పదాలు మాత్రమే అనుమతించబడతాయి. దయచేసి మీ వచనాన్ని తగ్గించండి.",
    "paste": "అతికించు",
    "copied": "కాపీ చేయబడింది",
    "copy_input": "ఇన్‌పుట్ కాపీ చేయి",
    "copy_output": "అవుట్‌పుట్ కాపీ చేయి",
    "clear": "క్లియర్",
    "paraphrase_btn": "పారాఫ్రేస్",
    "output_title": "అవుట్‌పుట్",
    "compare_versions": "వెర్షన్లను పోల్చండి",
    "mode_label": "మోడ్",
    "mode_standard": "ప్రామాణికం",
    "mode_fluency": "ఫ్లూయెన్సీ",
    "mode_formal": "అధికారికం",
    "mode_academic": "విద్యా విషయక",
    "mode_creative": "సృజనాత్మక",
    "mode_expand": "విస్తరించు",
    "mode_shorten": "కుదించు",
    "mode_simple": "సరళమైన",
    "words_label": "పదాలు",
    "regenerate": "మళ్లీ సృష్టించు",
    "swap_text": "వచనాన్ని మార్చు",
    "no_history_yet": "ఇంకా చరిత్ర లేదు",
    "history_stored_locally": "పారాఫ్రేస్ చేయబడిన అంశాలు స్వయంచాలకంగా స్థానికంగా నిల్వ చేయబడతాయి.",
    "paraphrase_now": "ఇప్పుడే పారాఫ్రేస్ చేయండి",
    "no_favorites_saved": "ఇష్టమైనవి ఏవీ సేవ్ చేయబడలేదు",
    "star_records_desc": "త్వరిత సూచన కోసం వాటిని సేవ్ చేయడానికి చరిత్రలోని రికార్డులపై స్టార్ గుర్తు ఉంచండి.",
    "view_history": "చరిత్రను చూడండి",
    "writing_insights": "వ్రాత అంతర్దృష్టులు",
    "refresh": "రిఫ్రెష్",
    "analyzing_insights": "వ్యాకరణం, చదవడానికి వీలుగా ఉండటం & స్వరాన్ని విశ్లేషిస్తోంది...",
    "no_text_analyze": "విశ్లేషించడానికి వచనం లేదు",
    "write_text_now": "ఇప్పుడే వచనాన్ని రాయండి",
    "readability_analysis": "చదివే సౌలభ్యం విశ్లేషణ",
    "writing_tone": "వ్రాత స్వరం",
    "confidence_label": "నమ్మకం",
    "grammar_mechanics": "వ్యాకరణం & మెకానిక్స్",
    "clean_grammar_desc": "మీ వ్యాకరణం శుభ్రంగా ఉంది! స్పెల్లింగ్ లేదా స్పేసింగ్ లోపాలు కనుగొనబడలేదు.",
    "style_recommendations": "శైలి సిఫార్సులు",
    "clean_style_desc": "అద్భుతమైన వ్రాత శైలి! శైలీకృత ప్రవాహ సూచనలు ఏవీ లేవు.",
    "removals": "తొలగించినవి",
    "additions": "జోడించినవి",
    "modified_synonyms": "సవరించినవి/పర్యాయపదాలు",
    "original_text_title": "అసలు వచనం",
    "paraphrased_text_title": "పారాఫ్రేస్ చేయబడిన వచనం",
    "paraphrase_details": "పారాఫ్రేస్ వివరాలు",
    "original": "అసలు",
    "paraphrased": "పారాఫ్రేస్ చేయబడింది",
    "created_at": "సృష్టించబడింది",
    "delete": "తొలగించు",
    "favorite": "ఇష్టమైనవి",
    "unstar": "అన్‌స్టార్",
    "reuse": "మళ్లీ ఉపయోగించు",
    "done": "పూర్తయింది",

    // Profile Screen
    "profile_header": "ప్రొఫైల్",
    "preferences": "ప్రాధాన్యతలు",
    "notifications": "నోటిఫికేషన్లు",
    "dark_mode": "డార్క్ మోడ్",
    "quick_actions": "త్వరిత చర్యలు",
    "edit_profile": "ప్రొఫైల్ సవరించండి",
    "app_settings": "యాప్ సెట్టింగులు",
    "language": "భాష",
    "language_subtitle": "అప్లికేషన్ ఇంటర్‌ఫేస్ కోసం మీకు నచ్చిన భాషను ఎంచుకోండి",
    "help_support": "సహాయం & మద్దతు",
    "logout": "లాగ్ అవుట్",

    // Help & Support Screen
    "faq_title": "తరచుగా అడిగే ప్రశ్నలు",
    "faq_sub": "ResearchMateAIని నావిగేట్ చేయడంలో మీకు సహాయపడటానికి శీఘ్ర సమాధానాలు",
    "faq_q1": "నేను CSVని ఎలా అప్‌లోడ్ చేయాలి?",
    "faq_a1": "'విశ్లేషణ' ట్యాబ్‌కు నావిగేట్ చేయండి, 'CSV ఎంచుకోండి' క్లిక్ చేయండి మరియు తక్షణ గణాంక నివేదికలను రూపొందించడానికి మీ పరికర నిల్వ నుండి ఏదైనా చెల్లుబాటు అయ్యే డేటాసెట్ ఫైల్‌ను ఎంచుకోండి.",
    "faq_q2": "పారాఫ్రేసర్ ఎలా పని చేస్తుంది?",
    "faq_a2": "ఇది అసలు వాస్తవాలు లేదా సందర్భాన్ని మార్చకుండా కస్టమ్ వ్రాత శైలులలో వచనాన్ని తిరిగి రాయడానికి అధునాతన అర్థ-సంరక్షణ విద్యా ఇంజిన్‌ను ఉపയോగిస్తుంది.",
    "faq_q3": "నేను పరిశోధన శీర్షికలను బుక్‌మార్క్ చేయవచ్చా?",
    "faq_a3": "అవును! ఉత్పత్తి చేయబడిన ఏదైనా పరిశోధన అంశం కార్డ్‌లోని బుక్‌మార్క్ చిహ్నాన్ని క్లిక్ చేయడం ద్వారా దానిని మీ ఇష్టమైన వాటి సేకరణకు తక్షణమే సేవ్ చేయండి.",
    "faq_q4": "నా పరిశోధన చరిత్ర ఎక్కడ సేవ్ చేయబడింది?",
    "faq_a4": "మీ విద్యాపరమైన పారాఫ్రేస్‌లు, అంతర్దృష్టులు మరియు డేటాసెట్‌లు అన్నీ మీ లోకల్ హోസ്റ്റ് సర్వర్‌లో సురક્ષितంగా సేవ్ చేయబడతాయి.",
    "submit_ticket": "సపోర్ట్ టికెట్ సమర్పించండి",
    "submit_ticket_sub": "అనుకూల సహాయం కావాలా? మా బృందానికి వివరణాత్మక విచారణను పంపండి.",
    "request_type": "అభ్యర్థన రకం",
    "bug_report": "బగ్ నివేదిక",
    "feature_request": "ఫీచర్ అభ్యర్థన",
    "question": "ప్రశ్న",
    "email_address": "మీ ఈమెయిల్ చిరునామా",
    "email_placeholder": "ఉదా. researcher@university.edu",
    "message_details": "సందేశ వివరాలు",
    "message_placeholder": "మీ సమస్య లేదా అభ్యర్థనను వివరంగా వివరించండి...",
    "submit_request": "మద్దతు అభ్యర్థనను సమర్పించండి",
    "required_fields": "తప్పనిసరి ఫీల్డ్‌లు",
    "required_fields_message": "దయచేసి మీ ఈమెయిల్ మరియు ఫీడ్‌బ్యాక్ సందేశం రెండింటినీ నమోదు చేయండి.",
    "invalid_email": "చెల్లని ఈమెయిల్",
    "invalid_email_message": "దయచేసి చెల్లుబాటు అయ్యే ఈమెయిల్ చిరునామాను నమోదు చేయండి.",
    "ticket_submitted": "టికెట్ సమర్పించబడింది",
    "ticket_submitted_message": "మీ మద్దతు అభ్యర్థన నమోదు చేయబడింది. మా మద్దతు బృందం త్వరలో మిమ్మల్ని సంప్రదిస్తుంది!",

    // Additions for missing strings
    "email_address_placeholder": "ఇమెయిల్ చిరునామా",
    "password_placeholder": "పాస్‌వర్డ్",
    "first_name_placeholder": "మొదటి పేరు",
    "last_name_placeholder": "చివరి పేరు",
    "username_placeholder": "వినియోగదారు పేరు",
    "mobile_number_placeholder": "మొబైల్ నంబర్",
    "confirm_password_placeholder": "పాస్‌వర్డ్‌ను నిర్ధారించండి",
    "forgot_password_btn": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "send_reset_code": "రీసెట్ కోడ్ పంపండి",
    "verify_code": "కోడ్ ధృవీకరించండి",
    "new_password_placeholder": "కొత్త పాస్‌వర్డ్",
    "confirm_new_password_placeholder": "కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి",
    "save_new_password": "కొత్త పాస్‌వర్డ్ సేవ్ చేయండి",
    "cancel_back_to_login": "రద్దు చేయి & లాగిన్‌కు తిరిగి వెళ్ళు",
    "back_to_login": "లాగిన్‌కు తిరిగి వెళ్ళు",
    "login_btn": "లాగిన్",
    "signup_btn": "సైన్ అప్",
    "verify_otp_btn": "OTP ని ధృవీకరించండి",
    "full_name_placeholder": "పూర్తి పేరు",
    "bio_placeholder": "బయో (ఉదా. డేటా సైంటిస్ట్)",
    "save_profile_btn": "ప్రొఫైల్ సేవ్ చేయండి",
    "search_saved_placeholder": "శీర్షిక, డొమైన్, డిపార్ట్‌మెంట్ ద్వారా శోధించండి...",
    "open_plan_btn": "ప్రణాళికను తెరవండి",
    "research_dashboard_title": "పరిశోధన డాష్‌బోర్డ్",
    "favorite_papers_title": "ఇష్టమైన పేపర్లు",
    "paper_intelligence_title": "పేపర్ ఇంటెలిజెన్స్",
    "abstract_title": "సారాంశం",
    "key_findings_title": "ముఖ్య అన్వేషణలు",
    "contributions_title": "సహకారం",
    "configure_graph_labels": "గ్రాఫ్ లేబుల్‌లను కాన్ఫిగర్ చేయండి",
    "graph_title_label": "గ్రాఫ్ శీర్షిక",
    "x_axis_label": "X-యాక్సిస్ లేబుల్",
    "y_axis_label": "Y-యాక్సిస్ లేబుల్",
    "graph_title_placeholder": "ఉదా. పోలిక గ్రాఫ్",
    "x_axis_placeholder": "ఉదా. పారామితులు",
    "y_axis_placeholder": "ఉదా. విలువ",
    "save_labels_btn": "లేబుల్‌లను సేవ్ చేయండి"
  },
  Tamil: {
    // Navigation / Tabs
    "home": "முகப்பு",
    "datasets": "தரவுத்தொகுப்புகள்",
    "analysis": "பகுப்பாய்வு",
    "tools": "கருவிகள்",
    "profile": "சுயவிவரம்",
    "history": "வரலாறு",
    "favorites": "பிடித்தவை",
    "insights": "நுண்ணறிவு",

    // General & Onboarding
    "welcome": "ResearchMateAI க்கு வரவேற்கிறோம்",
    "continue": "தொடரவும்",
    "skip": "தவிர்",
    "next": "அடுத்து",
    "get_started": "தொடங்குங்கள்",
    "onboarding1_title": "ஆராய்ச்சி யோசனைகளை உருவாக்குங்கள்",
    "onboarding1_sub": "உங்கள் துறை மற்றும் களத்திற்கு ஏற்ப ஸ்மார்ட் தலைப்பு பரிந்துரைகளை நொடிகளில் பெறுங்கள்.",
    "onboarding2_title": "தொடர்புடைய தரவுத்தொகுப்புகளைக் கண்டறியவும்",
    "onboarding2_sub": "நம்பகமான ஆதாரங்களில் இருந்து ஆயிரக்கணக்கான ஆராய்ச்சி தரவுத்தொகுப்புகளை உடனடியாகத் தேடுங்கள்.",
    "onboarding3_title": "உள்ளடக்கத்தை பகுப்பாய்வு செய்து மேம்படுத்துங்கள்",
    "onboarding3_sub": "தரவுத்தொகுப்புகளைப் பதிவேற்றவும், முடிவுகளைப் பகுப்பாய்வு செய்யவும் மற்றும் கல்வி உள்ளடக்கத்தை எளிதாக பாராபிரேஸ் செய்யவும்.",

    // Authentication
    "welcome_back": "மீண்டும் வருக 👋",
    "login_phone_title": "உங்கள் தொலைபேசி எண்ணுடன் உள்நுழையவும்",
    "enter_phone_placeholder": "தொலைபேசி எண்ணை உள்ளிடவும்",
    "sendOtp": "OTP அனுப்பவும்",
    "or": "அல்லது",
    "continue_google": "கூகுள் மூலம் தொடரவும்",
    "verify_otp_header": "OTP சரிபார்க்கவும்",
    "verify_otp_desc": "உங்கள் கைபேசி எண்ணுக்கு அனுப்பப்பட்ட 4 இலக்க குறியீட்டை உள்ளிடவும்",
    "verify": "சரிபார்த்து உள்நுழையவும்",
    "resend_otp": "மீண்டும் OTP அனுப்பவும்",

    // Dashboard Home
    "ai_research_assistant": "AI ஆராய்ச்சி உதவியாளர்",
    "smart_tools_desc": "கல்வி வெற்றிக்கு ஸ்மார்ட் கருவிகள்",
    "quick_access": "விரைவான அணுகல்",
    "title_generator": "தலைப்பு ஜெனரேட்டர்",
    "generate_topics_desc": "ஆராய்ச்சி தலைப்புகளை உருவாக்குங்கள்",
    "explore_datasets": "தரவுத்தொகுப்புகளை ஆராயுங்கள்",
    "analyze_csv_desc": "CSV தரவை பகுப்பாய்வு செய்யுங்கள்",
    "rewrite_content": "உள்ளடக்கத்தை மீண்டும் எழுதுங்கள்",

    // Title Generator Screen
    "research_title_gen": "ஆராய்ச்சி தலைப்பு ஜெனரேட்டர்",
    "title_gen_subtitle": "AI-இயக்கப்படும் திட்டம் மற்றும் ஆராய்ச்சி யோசனைகளை உடனடியாக உருவாக்குங்கள்",
    "department_label": "துறை",
    "domain_label": "களம்",
    "generate_btn": "தலைப்புகளை உருவாக்கு",
    "generated_topics": "உருவாக்கப்பட்ட தலைப்புகள்",
    "see_all": "அனைத்தையும் பார்",
    "generated_just_now": "இப்போது உருவாக்கப்பட்டது",
    "open": "திற",
    "empty_state_title": "ஆராய்ச்சி தலைப்புகளை உருவாக்கத் தொடங்குங்கள்",
    "empty_state_sub": "உங்கள் துறை மற்றும் களத்தைத் தேர்ந்தெடுத்து, தலைப்புகளை உருவாக்கு என்பதைத் தட்டவும்.",
    "select_dept_modal": "துறையைத் தேர்ந்தெடுக்கவும்",
    "select_domain_modal": "களத்தைத் தேர்ந்தெடுக்கவும்",
    "research": "ஆராய்ச்சி",
    "explore_research_papers": "ஆராய்ச்சி கட்டுரைகளை ஆராயுங்கள்",

    // Dataset Screen
    "discover_datasets": "தரவுத்தொகுப்புகளைக் கண்டறியவும்",
    "find_datasets_subtitle": "ஆராய்ச்சி மற்றும் AI திட்டங்களுக்கான தரவுத்தொகுப்புகளைக் கண்டறியவும்",
    "search_dataset_placeholder": "தரவுத்தொகுப்புகளைத் தேடுங்கள்...",
    "fetching_datasets": "பிரீமியம் தரவுத்தொகுப்புகளைப் பெறுகிறது...",
    "search_failed": "தேடல் தோல்வியடைந்தது",
    "retry_search": "மீண்டும் முயற்சிக்கவும்",
    "no_datasets_found": "தரவுத்தொகுப்புகள் எதுவும் இல்லை",
    "try_another_topic": "'காலநிலை', 'சுகாதாரம்' அல்லது 'நிதி' போன்ற மற்றொரு தலைப்பைத் தேட முயற்சிக்கவும்",
    "open_dataset": "தரவுத்தொகுப்பைத் திற",

    // CSV Analysis Screen
    "dataset_report": "தரவுத்தொகுப்பு அறிக்கை",
    "csv_analysis": "CSV பகுப்பாய்வு",
    "upload_analyze_subtitle": "ஆராய்ச்சி தரவுத்தொகுப்புகளைப் பதிவேற்றி பகுப்பாய்வு செய்யவும்",
    "upload_csv": "CSV கோப்பை பதிவேற்றவும்",
    "select_dataset_analysis": "AI-இயக்கப்படும் பகுப்பாய்விற்கு உங்கள் தரவுத்தொகுப்பைக் கண்டறியவும்",
    "analyzing": "பகுப்பாய்வு செய்கிறது...",
    "choose_csv": "CSV ஐத் தேர்ந்தெடு",
    "uploading_parsing": "தரவுத்தொகுப்பைப் பதிவேற்றி பகுப்பாய்வு செய்கிறது...",

    // Academic Paraphraser Screen
    "ai_paraphraser": "AI பாராபிரேசர்",
    "rewrite_text_subtitle": "பல எழுத்து பாணிகளுடன் உரையை மீண்டும் எழுதுங்கள்",
    "paste_or_type": "உரையை இங்கே ஒட்டவும் அல்லது தட்டச்சு செய்யவும்...",
    "characters": "எழுத்துக்கள்",
    "words": "வார்த்தைகள்",
    "max_words_warning": "அதிகபட்சம் 200 வார்த்தைகள் மட்டுமே அனுமதிக்கப்படும். தயவுசெய்து உங்கள் உரையைச் சுருக்கவும்.",
    "paste": "ஒட்டு",
    "copied": "நகலெடுக்கப்பட்டது",
    "copy_input": "உள்ளீட்டை நகலெடு",
    "copy_output": "வெளியீட்டை நகலெடு",
    "clear": "அழி",
    "paraphrase_btn": "பாராபிரேஸ்",
    "output_title": "வெளியீடு",
    "compare_versions": "பதிப்புகளை ஒப்பிடுக",
    "mode_label": "முறை",
    "mode_standard": "நிலையானது",
    "mode_fluency": "சரளம்",
    "mode_formal": "முறையானது",
    "mode_academic": "கல்விசார்",
    "mode_creative": "ஆக்கபூர்வமான",
    "mode_expand": "விரிவாக்கு",
    "mode_shorten": "சுருக்கு",
    "mode_simple": "எளிய",
    "words_label": "வார்த்தைகள்",
    "regenerate": "மீண்டும் உருவாக்கு",
    "swap_text": "உரையை மாற்று",
    "no_history_yet": "வரலாறு எதுவும் இல்லை",
    "history_stored_locally": "பாராபிரேஸ் செய்யப்பட்ட பொருட்கள் தானாகவே சேமிக்கப்படும்.",
    "paraphrase_now": "இப்போது பாராபிரேஸ் செய்",
    "no_favorites_saved": "பிடித்தவை எதுவும் சேமிக்கப்படவில்லை",
    "star_records_desc": "விரைவான குறிப்பிற்கு அவற்றைச் சேமிக்க வரலாற்றில் உள்ள பதிவுகளுக்கு நட்சத்திரக் குறியிடவும்.",
    "view_history": "வரலாற்றைப் பார்",
    "writing_insights": "எழுத்து நுண்ணறிவு",
    "refresh": "புதுப்பி",
    "analyzing_insights": "இலக்கணம், வாசிப்புத் தன்மை மற்றும் தொனியைப் பகுப்பாய்வு செய்கிறது...",
    "no_text_analyze": "பகுப்பாய்வு செய்ய உரை இல்லை",
    "write_text_now": "இப்போது உரையை எழுது",
    "readability_analysis": "வாசிப்புத்திறன் பகுப்பாய்வு",
    "writing_tone": "எழுதும் தொனி",
    "confidence_label": "நம்பிக்கை",
    "grammar_mechanics": "இலக்கணம் & இயக்கவியல்",
    "clean_grammar_desc": "உங்கள் இலக்கணம் சுத்தமாக உள்ளது! எழுத்துப்பிழை அல்லது இடைவெளி பிழைகள் எதுவும் கண்டறியப்படவில்லை.",
    "style_recommendations": "பாணி பரிந்துரைகள்",
    "clean_style_desc": "சிறந்த எழுத்து நடை! எந்த பாணி ஓட்ட பரிந்துரைகளும் இல்லை.",
    "removals": "நீக்கப்பட்டவை",
    "additions": "சேர்க்கப்பட்டவை",
    "modified_synonyms": "மாற்றப்பட்டவை/இணைச்சொற்கள்",
    "original_text_title": "அசல் உரை",
    "paraphrased_text_title": "பாராபிரேஸ் செய்யப்பட்ட உரை",
    "paraphrase_details": "பாராபிரேஸ் விவரங்கள்",
    "original": "அசல்",
    "paraphrased": "பாராபிரேஸ் செய்யப்பட்டது",
    "created_at": "உருவாக்கப்பட்டது",
    "delete": "நீக்கு",
    "favorite": "பிடித்தவை",
    "unstar": "நட்சத்திரத்தை நீக்கு",
    "reuse": "மீண்டும் பயன்படுத்து",
    "done": "முடிந்தது",

    // Profile Screen
    "profile_header": "சுயவிவரம்",
    "preferences": "விருப்பத்தேர்வுகள்",
    "notifications": "அறிவிப்புகள்",
    "dark_mode": "இருண்ட பயன்முறை",
    "quick_actions": "விரைவான செயல்கள்",
    "edit_profile": "சுயவிவரத்தைத் திருத்து",
    "app_settings": "பயன்பாட்டு அமைப்புகள்",
    "language": "மொழி",
    "language_subtitle": "பயன்பாட்டு இடைமுகத்திற்கு உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    "help_support": "உதவி & ஆதரவு",
    "logout": "வெளியேறு",

    // Help & Support Screen
    "faq_title": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    "faq_sub": "ResearchMateAI ஐ எளிதாகப் பயன்படுத்த சில விரைவான பதில்கள்",
    "faq_q1": "CSV கோப்பை எவ்வாறு பதிவேற்றுவது?",
    "faq_a1": "'பகுப்பாய்வு' பகுதிக்குச் சென்று, 'CSV ஐத் தேர்ந்தெடு' என்பதைக் கிளிக் செய்து, புள்ளிவிவர அறிக்கைகளைப் பெற உங்கள் சாதனத்திலிருந்து ஏதேனும் ஒரு CSV கோப்பைத் தேர்ந்தெடுக்கவும்.",
    "faq_q2": "பாராபிரேசர் எவ்வாறு செயல்படுகிறது?",
    "faq_a2": "இஃது அசல் உண்மைகளையோ சூழலையோ மாற்றாமல், கல்வி எழுத்து நடைகளில் உரையை மீண்டும் எழுத மேம்பட்ட தொழில்நுட்பத்தைப் பயன்படுத்துகிறது.",
    "faq_q3": "ஆராய்ச்சி தலைப்புகளைச் சேமிக்க முடியுமா?",
    "faq_a3": "ஆம்! உருவாக்கப்பட்ட எந்தவொரு ஆராய்ச்சி தலைப்பு கார்டிலும் உள்ள புக்மார்க் குறியீட்டைக் கிளிக் செய்வதன் மூலம் அதை உடனடியாகச் சேமிக்கலாம்.",
    "faq_q4": "எனது ஆராய்ச்சி வரலாறு எங்கே சேமிக்கப்படுகிறது?",
    "faq_a4": "உங்கள் கல்விப் பாராபிரேஸ்கள், நுண்ணறிவுகள் மற்றும் தரவுத்தொகுப்புகள் அனைத்தும் உங்கள் சாதனத்தில் பாதுகாப்பாகச் சேമിக்கப்படும்.",
    "submit_ticket": "உதவிக் கோரிக்கையைச் சமர்ப்பிக்கவும்",
    "submit_ticket_sub": "உங்களுக்கு தனிப்பயன் உதவி தேவையா? எங்கள் குழுவிற்கு விரிவான கேள்விகளை அனுப்பவும்.",
    "request_type": "கோரிக்கை வகை",
    "bug_report": "பிழை அறிக்கை",
    "feature_request": "வசதி கோரிக்கை",
    "question": "கேள்வி",
    "email_address": "உங்கள் மின்னஞ்சல் முகவரி",
    "email_placeholder": "உதாரணம்: researcher@university.edu",
    "message_details": "செய்தி விவரங்கள்",
    "message_placeholder": "உங்கள் பிரச்சனை அல்லது கோரிக்கையை விரிவாக விவரிக்கவும்...",
    "submit_request": "உதவிக் கோரிக்கையைச் சமர்ப்பிக்கவும்",
    "required_fields": "தேவையான புலங்கள்",
    "required_fields_message": "உங்கள் மின்னஞ்சல் மற்றும் கருத்துச் செய்தியை உள்ளிடவும்.",
    "invalid_email": "தவறான மின்னஞ்சல்",
    "invalid_email_message": "முறையான மின்னஞ்சல் முகவரியை உள்ளிடவும்.",
    "ticket_submitted": "கோரிக்கை சமர்ப்பிக்கப்பட்டது",
    "ticket_submitted_message": "உங்கள் உதவிக் கோரிக்கை பதிவு செய்யப்பட்டுள்ளது. எங்கள் ஆதரவுக் குழு விரைவில் உங்களைத் தொடர்பு கொள்ளும்!",

    // Additions for missing strings
    "email_address_placeholder": "மின்னஞ்சல் முகவரி",
    "password_placeholder": "கடவுச்சொல்",
    "first_name_placeholder": "முதல் பெயர்",
    "last_name_placeholder": "கடைசி பெயர்",
    "username_placeholder": "பயனர்பெயர்",
    "mobile_number_placeholder": "கைபேசி எண்",
    "confirm_password_placeholder": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    "forgot_password_btn": "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    "send_reset_code": "மீட்டமை குறியீட்டை அனுப்பு",
    "verify_code": "குறியீட்டை சரிபார்க்கவும்",
    "new_password_placeholder": "புதிய கடவுச்சொல்",
    "confirm_new_password_placeholder": "புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    "save_new_password": "புதிய கடவுச்சொல்லை சேமிக்கவும்",
    "cancel_back_to_login": "ரத்து செய்து உள்நுழைவுக்குத் திரும்பு",
    "back_to_login": "உள்நுழைவுக்குத் திரும்பு",
    "login_btn": "உள்நுழை",
    "signup_btn": "பதிவுபெறு",
    "verify_otp_btn": "OTP ஐ சரிபார்க்கவும்",
    "full_name_placeholder": "முழு பெயர்",
    "bio_placeholder": "சுயசரிதை (எ.கா. தரவு விஞ்ஞானி)",
    "save_profile_btn": "சுயவிவரத்தை சேமி",
    "search_saved_placeholder": "தலைப்பு, டொமைன், துறை மூலம் தேடுங்கள்...",
    "open_plan_btn": "திட்டத்தைத் திற",
    "research_dashboard_title": "ஆராய்ச்சி டாஷ்போர்டு",
    "favorite_papers_title": "பிடித்த தாள்கள்",
    "paper_intelligence_title": "காகித நுண்ணறிவு",
    "abstract_title": "சுருக்கம்",
    "key_findings_title": "முக்கிய கண்டுபிடிப்புகள்",
    "contributions_title": "பங்களிப்புகள்",
    "configure_graph_labels": "வரைபட லேபிள்களை உள்ளமைக்கவும்",
    "graph_title_label": "வரைபடத்தின் தலைப்பு",
    "x_axis_label": "X-அச்சு லேபிள்",
    "y_axis_label": "Y-அச்சு லேபிள்",
    "graph_title_placeholder": "எ.கா. ஒப்பீடு வரைபடம்",
    "x_axis_placeholder": "எ.கா. அளவுருக்கள்",
    "y_axis_placeholder": "எ.கா. மதிப்பு",
    "save_labels_btn": "லேபிள்களைச் சேமி"
  },
  Malayalam: {
    // Navigation / Tabs
    "home": "ഹോം",
    "datasets": "ഡാറ്റാസെറ്റുകൾ",
    "analysis": "വിശകലനം",
    "tools": "ഉപകരണങ്ങൾ",
    "profile": "പ്രൊഫൈൽ",
    "history": "ചരിത്രം",
    "favorites": "പ്രിയപ്പെട്ടവ",
    "insights": "വിശകലനം",

    // General & Onboarding
    "welcome": "ResearchMateAI-ലേക്ക് സ്വാഗതം",
    "continue": "തുടരുക",
    "skip": "ഒഴിവാക്കുക",
    "next": "അടുത്തത്",
    "get_started": "ആരംഭിക്കുക",
    "onboarding1_title": "ഗവേഷണ ആശയങ്ങൾ സൃഷ്ടിക്കുക",
    "onboarding1_sub": "നിങ്ങളുടെ വകുപ്പിനും മേഖലയ്ക്കും അനുയോജ്യമായ സ്മാർട്ട് വിഷയം നിർദ്ദേശങ്ങൾ നിമിഷങ്ങൾക്കകം നേടുക.",
    "onboarding2_title": "പ്രസക്തമായ ഡാറ്റാസെറ്റുകൾ കണ്ടെത്തുക",
    "onboarding2_sub": "വിശ്വസനീയമായ ഉറവിടങ്ങളിൽ നിന്ന് ആയിരക്കണക്കിന് ഗവേഷണ ഡാറ്റാസെറ്റുകൾ തൽക്ഷണം തിരയുക.",
    "onboarding3_title": "ഉള്ളടക്കം വിശകലനം ചെയ്യുകയും മെച്ചപ്പെടുത്തുകയും ചെയ്യുക",
    "onboarding3_sub": "ഡാറ്റാസെറ്റുകൾ അപ്‌ലോഡ് ചെയ്യുക, ഫലങ്ങൾ വിശകലനം ചെയ്യുക, അക്കാദമിക് ഉള്ളടക്കം എളുപ്പത്തിൽ പാരാഫ്രേസ് ചെയ്യുക.",

    // Authentication
    "welcome_back": "വീണ്ടും സ്വാഗതം 👋",
    "login_phone_title": "ഫോൺ നമ്പർ ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക",
    "enter_phone_placeholder": "ഫോൺ നമ്പർ നൽകുക",
    "sendOtp": "OTP അയയ്ക്കുക",
    "or": "അല്ലെങ്കിൽ",
    "continue_google": "ഗൂഗിൾ ഉപയോഗിച്ച് തുടരുക",
    "verify_otp_header": "OTP പരിശോധിക്കുക",
    "verify_otp_desc": "മൊബൈൽ നമ്പറിലേക്ക് അയച്ച 4-അക്ക കോഡ് നൽകുക",
    "verify": "പരിശോധിച്ച് ലോഗിൻ ചെയ്യുക",
    "resend_otp": "OTP വീണ്ടും അയയ്ക്കുക",

    // Dashboard Home
    "ai_research_assistant": "AI ഗവേഷണ സഹായി",
    "smart_tools_desc": "വിദ്യാഭ്യാസ വിജയത്തിന് സ്മാർട്ട് ടൂളുകൾ",
    "quick_access": "ദ്രുത പ്രവേശനം",
    "title_generator": "ടൈറ്റിൽ ജനറേറ്റർ",
    "generate_topics_desc": "ഗവേഷണ വിഷയങ്ങൾ സൃഷ്ടിക്കുക",
    "explore_datasets": "ഡാറ്റാസെറ്റുകൾ പര്യവേക്ഷണം ചെയ്യുക",
    "analyze_csv_desc": "CSV ഡാറ്റ വിശകലനം ചെയ്യുക",
    "rewrite_content": "ഉള്ളടക്കം തിരുത്തിയെഴുതുക",

    // Title Generator Screen
    "research_title_gen": "ഗവേഷണ ടൈറ്റിൽ ജനറേറ്റർ",
    "title_gen_subtitle": "AI-അധിഷ്ഠിത പ്രോജക്റ്റ്, ഗവേഷണ ആശയങ്ങൾ തൽക്ഷണം സൃഷ്ടിക്കുക",
    "department_label": "വകുപ്പ്",
    "domain_label": "മേഖല",
    "generate_btn": "ശീർഷകങ്ങൾ സൃഷ്ടിക്കുക",
    "generated_topics": "സൃഷ്ടിച്ച വിഷയങ്ങൾ",
    "see_all": "എല്ലാം കാണുക",
    "generated_just_now": "ഇപ്പോൾ സൃഷ്ടിച്ചത്",
    "open": "തുറക്കുക",
    "empty_state_title": "ഗവേഷണ ശീർഷകങ്ങൾ സൃഷ്ടിക്കാൻ ആരംഭിക്കുക",
    "empty_state_sub": "വകുപ്പും മേഖലയും തിരഞ്ഞെടുക്കുക, തുടർന്ന് ശീർഷകങ്ങൾ സൃഷ്ടിക്കുക എന്നത് ടാപ്പുചെയ്യുക.",
    "select_dept_modal": "വകുപ്പ് തിരഞ്ഞെടുക്കുക",
    "select_domain_modal": "മേഖല തിരഞ്ഞെടുക്കുക",

    // Dataset Screen
    "discover_datasets": "ഡാറ്റാസെറ്റുകൾ കണ്ടെത്തുക",
    "find_datasets_subtitle": "ഗവേഷണത്തിനും AI പ്രോജക്റ്റുകൾക്കുമായി ഡാറ്റാസെറ്റുകൾ കണ്ടെത്തുക",
    "search_dataset_placeholder": "ഡാറ്റാസെറ്റുകൾ തിരയുക...",
    "fetching_datasets": "പ്രീമിയം ഡാറ്റാസെറ്റുകൾ ലഭ്യമാക്കുന്നു...",
    "search_failed": "തിരച്ചിൽ പരാജയപ്പെട്ടു",
    "retry_search": "തിരച്ചിൽ വീണ്ടും ശ്രമിക്കുക",
    "no_datasets_found": "ഡാറ്റാസെറ്റുകൾ ഒന്നും കണ്ടെത്തിയില്ല",
    "try_another_topic": "'കാലാവസ്ഥ', 'ആരോഗ്യം' അല്ലെങ്കിൽ 'ധനകാര്യം' പോലുള്ള മറ്റൊരു വിഷയം തിരയാൻ ശ്രമിക്കുക",
    "open_dataset": "ഡാറ്റാസെറ്റ് തുറക്കുക",

    // CSV Analysis Screen
    "dataset_report": "ഡാറ്റാസെറ്റ് റിപ്പോർട്ട്",
    "csv_analysis": "CSV വിശകലനം",
    "upload_analyze_subtitle": "ഗവേഷണ ഡാറ്റാസെറ്റുകൾ അപ്‌ലോഡ് ചെയ്ത് വിശകലനം ചെയ്യുക",
    "upload_csv": "CSV ഫയൽ അപ്‌ലോഡ് ചെയ്യുക",
    "select_dataset_analysis": "AI-അധിഷ്ഠിത വിശകലനത്തിനായി നിങ്ങളുടെ ഡാറ്റാസെറ്റ് തിരഞ്ഞെടുക്കുക",
    "analyzing": "വിശകലനം ചെയ്യുന്നു...",
    "choose_csv": "CSV തിരഞ്ഞെടുക്കുക",
    "uploading_parsing": "ഡാറ്റാസെറ്റ് അപ്‌ലോഡ് ചെയ്ത് വിശകലനം ചെയ്യുന്നു...",

    // Academic Paraphraser Screen
    "ai_paraphraser": "AI പാരാഫ്രേസർ",
    "rewrite_text_subtitle": "ഒന്നിലധികം എഴുത്ത് ശൈലികളിൽ ടെക്സ്റ്റ് തിരുത്തിയെഴുതുക",
    "paste_or_type": "ടെക്സ്റ്റ് ഇവിടെ നൽകുക അല്ലെങ്കിൽ ഒട്ടിക്കുക...",
    "characters": "അക്ഷരങ്ങൾ",
    "words": "വാക്കുകൾ",
    "max_words_warning": "പരമാവധി 200 വാക്കുകൾ മാത്രമേ അനുവദിക്കൂ. ദയവായി നിങ്ങളുടെ ടെക്സ്റ്റ് ചുരുക്കുക.",
    "paste": "പേസ്റ്റ്",
    "copied": "കോപ്പി ചെയ്തു",
    "copy_input": "ഇൻപുട്ട് കോപ്പി ചെയ്യുക",
    "copy_output": "ഔട്ട്പുട്ട് കോപ്പി ചെയ്യുക",
    "clear": "ക്ലിയർ",
    "paraphrase_btn": "പാരാഫ്രേസ്",
    "output_title": "ഔട്ട്പുട്ട്",
    "compare_versions": "പതിപ്പുകൾ താരതമ്യം ചെയ്യുക",
    "mode_label": "രീതി",
    "mode_standard": "സാധാരണ",
    "mode_fluency": "ഒഴുക്കോടെയുള്ള",
    "mode_formal": "ഔദ്യോഗിക",
    "mode_academic": "അക്കാദമിക്",
    "mode_creative": "ക്രിയേറ്റീവ്",
    "mode_expand": "വലുതാക്കുക",
    "mode_shorten": "ചെറുതാക്കുക",
    "mode_simple": "ലളിതം",
    "words_label": "വാക്കുകൾ",
    "regenerate": "വീണ്ടും സൃഷ്ടിക്കുക",
    "swap_text": "ടെക്സ്റ്റ് പരസ്പരം മാറ്റുക",
    "no_history_yet": "ചരിത്രം ലഭ്യമല്ല",
    "history_stored_locally": "പാരാഫ്രേസ് ചെയ്തവ സ്വയമേവ ഫോണിൽ സേവ് ചെയ്യപ്പെടുന്നതാണ്.",
    "paraphrase_now": "ഇപ്പോൾ പാരാഫ്രേസ് ചെയ്യുക",
    "no_favorites_saved": "പ്രിയപ്പെട്ടവ ഒന്നും സേവ് ചെയ്തിട്ടില്ല",
    "star_records_desc": "ദ്രുത റഫറൻസിനായി അവ സംരക്ഷിക്കാൻ ചരിത്രത്തിൽ കാണുന്നവ സ്റ്റാർ ചെയ്യുക.",
    "view_history": "ചരിത്രം കാണുക",
    "writing_insights": "എഴുത്ത് വിശകലനം",
    "refresh": "പുതുക്കുക",
    "analyzing_insights": "വ്യാകരണം, വായനാക്ഷമത, ശൈലി എന്നിവ വിശകലനം ചെയ്യുന്നു...",
    "no_text_analyze": "വിശകലനം ചെയ്യാൻ ടെക്സ്റ്റ് ലഭ്യമല്ല",
    "write_text_now": "ഇപ്പോൾ ടെക്സ്റ്റ് എഴുതുക",
    "readability_analysis": "വായനാക്ഷമത വിശകലനം",
    "writing_tone": "എഴുത്തിന്റെ ശൈലി",
    "confidence_label": "ആത്മവിശ്വാസം",
    "grammar_mechanics": "വ്യാകരണവും ഘടനയും",
    "clean_grammar_desc": "വ്യാകരണം മികച്ചതാണ്! അക്ഷരത്തെറ്റുകളോ സ്പേസിംഗ് തെറ്റുകളോ കണ്ടെത്തിയില്ല.",
    "style_recommendations": "ശൈലി നിർദ്ദേശങ്ങൾ",
    "clean_style_desc": "മികച്ച എഴുത്ത് ശൈലി! മറ്റ് മാറ്റങ്ങൾ ഒന്നും വരുത്തേണ്ടതില്ല.",
    "removals": "ഒഴിവാക്കിയവ",
    "additions": "ചേർത്തവ",
    "modified_synonyms": "തിരുത്തിയവ/പര്യായപദങ്ങൾ",
    "original_text_title": "യഥാർത്ഥ ടെക്സ്റ്റ്",
    "paraphrased_text_title": "പാരാഫ്രേസ് ചെയ്ത ടെക്സ്റ്റ്",
    "paraphrase_details": "പാരാഫ്രേസ് വിവരങ്ങൾ",
    "original": "യഥார்த்தം",
    "paraphrased": "പാരാഫ്രേസ് ചെയ്തത്",
    "created_at": "തയ്യാറാക്കിയത്",
    "delete": "ഇല്ലാതാക്കുക",
    "favorite": "പ്രിയപ്പെട്ടത്",
    "unstar": "അൺസ്റ്റാർ",
    "reuse": "വീണ്ടും ഉപയോഗിക്കുക",
    "done": "കഴിഞ്ഞു",

    // Profile Screen
    "profile_header": "പ്രൊഫൈൽ",
    "preferences": "മുൻഗണനകൾ",
    "notifications": "അറിയിപ്പുകൾ",
    "dark_mode": "ഡാർക്ക് മോഡ്",
    "quick_actions": "ദ്രുത നടപടികൾ",
    "edit_profile": "പ്രൊഫൈൽ തിരുത്തുക",
    "app_settings": "ആപ്പ് ക്രമീകരണങ്ങൾ",
    "language": "ഭാഷ",
    "language_subtitle": "ആപ്ലിക്കേഷൻ ഇൻ്റർഫേസിനായി നിങ്ങളുടെ താൽപ്പര്യമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക",
    "help_support": "സഹായവും പിന്തുണയും",
    "logout": "ലോഗ് ഔട്ട്",

    // Help & Support Screen
    "faq_title": "പതിവായി ചോദിക്കുന്ന ചോദ്യങ്ങൾ",
    "faq_sub": "ResearchMateAI എളുപ്പത്തിൽ ഉപയോഗിക്കാൻ ചില ദ്രുത ഉത്തരങ്ങൾ",
    "faq_q1": "ഞാൻ എങ്ങനെയാണ് ഒരു CSV അപ്‌ലോഡ് ചെയ്യുക?",
    "faq_a1": "'വിശകലനം' ടാബിലേക്ക് പോയി, 'CSV തിരഞ്ഞെടുക്കുക' ക്ലിക്ക് ചെയ്ത് സ്റ്റാറ്റിസ്റ്റിക്കൽ റിപ്പോർട്ടുകൾ ലഭിക്കാൻ നിങ്ങളുടെ ഉപകരണത്തിൽ നിന്ന് ഏതെങ്കിലും CSV ഫയൽ തിരഞ്ഞെടുക്കുക.",
    "faq_q2": "പാരാഫ്രേസർ എങ്ങനെയാണ് പ്രവർത്തിക്കുന്നത്?",
    "faq_a2": "യഥാർത്ഥ വസ്തുതകളോ സന്ദർഭമോ മാറ്റാതെ, വിവിധ എഴുത്ത് ശൈലികളിൽ വാചകം വീണ്ടും എഴുതാൻ ഇത് നൂതന സാങ്കേതികവിദ്യ ഉപയോഗിക്കുന്നു.",
    "faq_q3": "എനിക്ക് ഗവേഷണ തലക്കെട്ടുകൾ ബുക്ക്മാർക്ക് ചെയ്യാൻ കഴിയുമോ?",
    "faq_a3": "അതെ! ഏതെങ്കിലും ഗവേഷണ വിഷയം കാർഡിലെ ബുക്ക്മാർക്ക് ഐക്കണിൽ ക്ലിക്ക് ചെയ്ത് അത് ഉടനടി നിങ്ങളുടെ പ്രിയപ്പെട്ടവയിലേക്ക് സംരക്ഷിക്കുക.",
    "faq_q4": "എന്റെ ഗവേഷണ ചരിത്രം എവിടെയാണ് സംരക്ഷിക്കപ്പെടുന്നത്?",
    "faq_a4": "നിങ്ങളുടെ പാരാഫ്രേസുകൾ, വിശകലനങ്ങൾ, ഡാറ്റാസെറ്റുകൾ എന്നിവയെല്ലാം നിങ്ങളുടെ ഉപകരണത്തിൽ തന്നെ സുരക്ഷിതമായി സംരക്ഷിക്കപ്പെടുന്നു.",
    "submit_ticket": "ഒരു സപ്പോർട്ട് ടിക്കറ്റ് സമർപ്പിക്കുക",
    "submit_ticket_sub": "കൂടുതൽ സഹായം ആവശ്യമുണ്ടോ? ഞങ്ങളുടെ ടീമിന് വിശദമായ ഒരു സന്ദേശം അയക്കുക.",
    "request_type": "ആവശ്യപ്പെടുന്ന തരം",
    "bug_report": "ബഗ് റിപ്പോർട്ട്",
    "feature_request": "ഫീച്ചർ അഭ്യർത്ഥന",
    "question": "ചോദ്യം",
    "email_address": "നിങ്ങളുടെ ഇമെയിൽ വിലാസം",
    "email_placeholder": "ഉദാഹരണത്തിന്: researcher@university.edu",
    "message_details": "സന്ദേശത്തിന്റെ വിവരങ്ങൾ",
    "message_placeholder": "നിങ്ങളുടെ പ്രശ്നം അല്ലെങ്കിൽ ആവശ്യം വിശദമായി വിവരിക്കുക...",
    "submit_request": "സപ്പോർട്ട് റിക്വസ്റ്റ് സമർപ്പിക്കുക",
    "required_fields": "ആവശ്യമായ വിവരങ്ങൾ",
    "required_fields_message": "നിങ്ങളുടെ ഇമെയിലും സന്ദേശവും ദയവായി രേഖപ്പെടുത്തുക.",
    "invalid_email": "തെറ്റായ ഇമെയിൽ",
    "invalid_email_message": "സാധുവായ ഒരു ഇമെയിൽ വിലാസം നൽകുക.",
    "ticket_submitted": "ടിക്കറ്റ് സമർപ്പിച്ചു",
    "ticket_submitted_message": "നിങ്ങളുടെ സപ്പോർട്ട് റിക്വസ്റ്റ് രജിസ്റ്റർ ചെയ്തിട്ടുണ്ട്. ഞങ്ങളുടെ ടീം നിങ്ങളെ ഉടൻ ബന്ധപ്പെടും!",

    // Additions for missing strings
    "email_address_placeholder": "ഇമെയിൽ വിലാസം",
    "password_placeholder": "പാസ്‌വേഡ്",
    "first_name_placeholder": "ആദ്യത്തെ പേര്",
    "last_name_placeholder": "അവസാന പേര്",
    "username_placeholder": "ഉപയോക്തൃനാമം",
    "mobile_number_placeholder": "മൊബൈൽ നമ്പർ",
    "confirm_password_placeholder": "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    "forgot_password_btn": "പാസ്‌വേഡ് മറന്നുപോയോ?",
    "send_reset_code": "റീസെറ്റ് കോഡ് അയയ്ക്കുക",
    "verify_code": "കോഡ് പരിശോധിക്കുക",
    "new_password_placeholder": "പുതിയ പാസ്‌വേഡ്",
    "confirm_new_password_placeholder": "പുതിയ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    "save_new_password": "പുതിയ പാസ്‌വേഡ് സംരക്ഷിക്കുക",
    "cancel_back_to_login": "റദ്ദാക്കി ലോഗിനിലേക്ക് മടങ്ങുക",
    "back_to_login": "ലോഗിനിലേക്ക് മടങ്ങുക",
    "login_btn": "ലോഗിൻ",
    "signup_btn": "സൈൻ അപ്പ്",
    "verify_otp_btn": "OTP പരിശോധിക്കുക",
    "full_name_placeholder": "പൂർണ്ണമായ പേര്",
    "bio_placeholder": "ബയോ (ഉദാഹരണത്തിന്: ഡാറ്റാ സയന്റിസ്റ്റ്)",
    "save_profile_btn": "പ്രൊഫൈൽ സംരക്ഷിക്കുക",
    "search_saved_placeholder": "തലക്കെട്ട്, ഡൊമെയ്ൻ, വകുപ്പ് എന്നിവയിലൂടെ തിരയുക...",
    "open_plan_btn": "പ്ലാൻ തുറക്കുക",
    "research_dashboard_title": "ഗവേഷണ ഡാഷ്‌ബോർഡ്",
    "favorite_papers_title": "പ്രിയപ്പെട്ട പേപ്പറുകൾ",
    "paper_intelligence_title": "പേപ്പർ ഇന്റലിജൻസ്",
    "abstract_title": "സംഗ്രഹം",
    "key_findings_title": "പ്രധാന കണ്ടെത്തലുകൾ",
    "contributions_title": "സംഭാവനകൾ",
    "configure_graph_labels": "ഗ്രാഫ് ലേബലുകൾ കോൺഫിഗർ ചെയ്യുക",
    "graph_title_label": "ഗ്രാഫ് ശീർഷകം",
    "x_axis_label": "X-ആക്സിസ് ലേബൽ",
    "y_axis_label": "Y-ആക്സിസ് ലേബൽ",
    "graph_title_placeholder": "ഉദാഹരണത്തിന്: താരതമ്യ ഗ്രാഫ്",
    "x_axis_placeholder": "ഉദാഹരണത്തിന്: പരാമീറ്ററുകൾ",
    "y_axis_placeholder": "ഉദാഹരണത്തിന്: മൂല്യം",
    "save_labels_btn": "ലേബലുകൾ സംരക്ഷിക്കുക"
  }
};

export const useTranslation = () => {
  const [lang, setLang] = useState(currentLanguage);

  useEffect(() => {
    const listener = (newLang: string) => setLang(newLang);
    listeners.add(listener);
    return () => {
      listeners.delete(listener);
    };
  }, []);

  const t = (key: string): string => {
    const langTrans = translations[lang] || translations["English"];
    return langTrans[key] || translations["English"][key] || key;
  };

  return { t, currentLanguage: lang };
};
